### ISSUE TITLE
build error with lineage 14.1

### ISSUE THREAD

**Issue by ardadem** [thune-xiaobai/android_device_xiaomi_capricorn#3]
ninja: error: '/home/arda/lineage/out/target/product/capricorn/obj/STATIC_LIBRARIES/librecovery_ui_msm_intermediates/export_includes', needed by '/home/arda/lineage/out/target/product/capricorn/obj/EXECUTABLES/recovery_intermediates/import_includes', missing and no known rule to make it
make: *** [build/core/ninja.mk:152: ninja_wrapper] Error 1

**Comment by thune-xiaobai** [comment]
u need this: https://github.com/LineageOS/android_device_qcom_common

see https://github.com/thune-xiaobai/android_device_xiaomi_capricorn/blob/cm-14.1/lineage.dependencies#L3
